[package]
name = "debrepo"
version = "0.0.0"
publish = false
rust-version = "1.82"
edition = "2021"

[dev-dependencies]
criterion = "0.4"

[dependencies]
anyhow = "1"
ouroboros = "0.18"
async-trait = "0.1"
futures = "0.3"
futures-io = "0.3"
futures-util = "0.3"
pin-project = "1"
async-std = { version = "1", features = [ "attributes" ] }
async-tar = "0.5"
isahc = { version = "1", default-features = false, features = [ "http2" ] }
url = "2"
chrono = "0.4"
gpgme = "0.11.0"
digest = "0.10"
md-5 = "0.10"
sha1 = "0.10"
sha2 = "0.10"
hex = "0.4"
memchr = "2"
criterion = "0.4"
resolvo = "0.8.5"
smallvec = "1.13"
iterator-ext = "0.2.1"
log = "0.4.22"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4", features = ["derive", "env"] }
regex = "1.11"
tempfile = "3.15.0"
filetime = "0.2.25"
petgraph = { version = "0.7.1", default-features = false, features = [ "graphmap" ] }
itertools = "0.14.0"

[dependencies.async-compression]
version = "0.4"
features = [ "futures-io", "bzip2", "gzip", "zstd", "lzma", "xz" ]

[lib]
name = "debrepo"
path = "src/lib.rs"

[[bench]]
name = "control"
harness = false

[[bench]]
name = "version"
harness = false

[[bench]]
name = "solver"
harness = false

[[bin]]
name = "deb-repo"
path = "cmd/main.rs"
