# default manifest file for debian
[[archive]]
url = "https://ftp.debian.org/debian/"
snapshots = "https://snapshot.debian.org/archive/debian/@SNAPSHOTID@/"
snapshot = "20260221T221217Z"
suites = ["trixie", "trixie-updates", "trixie-backports"]
components = ["main", "contrib", "non-free"]

[[archive]]
url = "https://security.debian.org/debian-security/"
snapshots = "https://snapshot.debian.org/archive/debian-security/@SNAPSHOTID@/"
snapshot = "20260221T221217Z"
suites = ["trixie-security"]
components = ["main", "contrib", "non-free"]

[spec]
include = [
    "ca-certificates",
    "build-essential",
    "pkg-config",
    "devscripts",
    "libdistro-info-perl",
    "debhelper",
    "cargo (>= 1.89.0)",
    "debcargo",
    "dh-cargo",
    "libbz2-dev",
    "libcurl4-openssl-dev",
    "libgpg-error-dev",
    "libgpgme-dev",
    "liblz4-dev",
    "liblzma-dev",
    "libssl-dev",
    "libunistring-dev",
    "libzstd-dev",
]
