name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check environment
        run: |
          uname -a
          sudo mount
          cat /proc/self/uid_map
          whoami
          stat -f -c %T .
          sysctl fs.protected_regular
          sysctl fs.protected_symlinks
          sysctl fs.protected_hardlinks

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.1 # current debian stable
          components: rustfmt,clippy

      - name: Cache cargo registry + build
        uses: Swatinem/rust-cache@v2

      - name: Install system dependencies
        env: 
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            pkg-config \
            build-essential \
            debhelper \
            devscripts \
            libbz2-dev \
            libcurl4-openssl-dev \
            libgpg-error-dev \
            libgpgme-dev \
            liblz4-dev \
            liblzma-dev \
            libssl-dev \
            libunistring-dev \
            libzstd-dev \
            zlib1g-dev \
            podman

      - name: Install newer uidmap from Ubuntu 25.04
        run: |
          set -eux
          echo "deb http://archive.ubuntu.com/ubuntu plucky main" | sudo tee /etc/apt/sources.list.d/plucky.list
          printf "Package: *\nPin: release n=plucky\nPin-Priority: 100\n" | sudo tee /etc/apt/preferences.d/plucky
          sudo apt-get update
          sudo apt-get install -y -t plucky uidmap

      # - name: Check formatting
      #   run: cargo fmt --all -- --check
      #
      # - name: Run Clippy
      #   run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build

      # - name: Run tests
      #   run: cargo test

      - name: Cache debian build tree
        uses: actions/cache@v4
        with:
          path: |
            target/debian-build/**
            !target/debian-build/*.deb
            !target/debian-build/*.buildinfo
            !target/debian-build/*.changes
          key: ${{ runner.os }}-debian-build-${{ hashFiles('Cargo.lock', 'debian-build.amd64.lock') }}
          restore-keys: |
            ${{ runner.os }}-debian-build-

      - name: Build debian packages
        timeout-minutes: 10
        run: |
          whoami
          id
          printf "real=%s effective=%s\n" "$(id -ru)" "$(id -u)"
          echo subuid map
          cat /etc/subuid
          echo subgid map
          cat /etc/subgid
          make debian-packages

      # - name: Cache ubuntu build tree
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       target/ubuntu-build/**
      #       !target/ubuntu-build/*.deb
      #       !target/ubuntu-build/*.buildinfo
      #       !target/ubuntu-build/*.changes
      #     key: ${{ runner.os }}-ubuntu-build-${{ hashFiles('Cargo.lock', 'debian-build.amd64.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-ubuntu-build-
      #
      # - name: Build ubuntu packages
      #   run: make ubuntu-packages
      #
      # - name: Create GitHub Release
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       target/debian-build/*.deb
      #       target/ubuntu-build/*.deb
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
